version: 2.1
# Goal: 


jobs:
  build_h:
    docker:
      - image: cimg/python:3.14

    environment:
      NAME: Ayoob

    steps:
      - checkout
      - restore_cache:
          name: "Get last database run"
          key: clamav-db-$TEST
      - run:
          name: "Saying hello"
          command: echo "Hello $NAME 2"
      - run:
          name: "Installing Clamav"
          command: pip install cvdupdate 
      - run:
          name: "pulling database"
          command: cvd update
      - save_cache:
          name: "Save database"
          paths:
            - ~/.cvdupdate/database
          key: clamav-db-{{ epoch }} 
          when: on_success
        
workflows:
  build a hello world: 
    jobs:
      - build_h
