version: 2.1
# Goal: 

parameters:
  run-every-5:
    type: boolean
    default: false

jobs:
  build_h:
    docker:
      - image: cimg/python:3.14

    environment:
      NAME: Ayoob

    steps:
      - checkout
      - restore_cache:
          name: "Get last database run"
          key: clamav-db-  
      - run: echo "THE VERSION IS \n" 
      - run: jq '."dbs"["daily.cvd"]["local version"]' ~/.cvdupdate/state.json || true
      - run:
          name: "Saying hello"
          command: echo "Hello $NAME 2"
      - run:
          name: "Installing Clamav"
          command: pip install cvdupdate 
      - run:
          name: "pulling database"
          command: cvd update
      - run:
          name: "Download Jfrog CLI"
          command: curl -fL https://install-cli.jfrog.io | sh
      - run: echo "curl"
      - save_cache:
          name: "Save databasee"
          paths:
            - ~/.cvdupdate/
          key: clamav-db-{{ epoch }} 
          when: on_success
      - run:
          name: Testing project secret1
          command: echo $SECRET1
        
workflows:
  every-5:
    when: << pipeline.parameters.run-every-5 >>  
    jobs:
      - build_h
